[main]
; include=/home/b/.config/fuzzel/catppuccin.ini

font=FiraMono Nerd Font:size=12:slant=retina
dpi-aware=yes
prompt=››
icon-theme=ZafiroCircle

fields=name,exec,keywords,categories

terminal=alacritty -e

exit-on-keyboard-focus-loss=yes

[border]

[key-bindings]
